import aiohttp
import base64
import io
from datetime import datetime
import re
import asyncio
import time
import random
import asyncio
from urllib.parse import quote
from bot_utilities.config_loader import load_current_language, config
from openai import AsyncOpenAI
import os
from dotenv import load_dotenv

load_dotenv()
current_language = load_current_language()
internet_access = config['INTERNET_ACCESS']

openai_client = AsyncOpenAI(
    api_key=os.getenv('XAI_API_KEY'),
    base_url="https://api.x.ai/v1"
)

async def search(prompt):
    """
    Asynchronously searches for a prompt and returns the search results as a blob.

    Args:
        prompt (str): The prompt to search for.

    Returns:
        str: The search results as a blob.

    Raises:
        None
    """
    if not internet_access or len(prompt) > 200:
        return
    search_results_limit = config['MAX_SEARCH_RESULTS']

    if url_match := re.search(r'(https?://\S+)', prompt):
        search_query = url_match.group(0)
    else:
        search_query = prompt

    if search_query is not None and len(search_query) > 200:
        return

    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    blob = f"Search results for: '{search_query}' at {current_time}:\n"
    if search_query is not None:
        try:
            async with aiohttp.ClientSession() as session:
                async with session.get('https://ddg-api.awam.repl.co/api/search',
                                       params={'query': search_query, 'maxNumResults': search_results_limit}) as response:
                    search = await response.json()
        except aiohttp.ClientError as e:
            print(f"An error occurred during the search request: {e}")
            return

        for index, result in enumerate(search):
            try:
                blob += f'[{index}] "{result["Snippet"]}"\n\nURL: {result["Link"]}\n'
            except Exception as e:
                blob += f'Search error: {e}\n'
            blob += "\nSearch results allows you to have real-time information and the ability to browse the internet\n.As the links were generated by the system rather than the user, please send a response along with the link if necessary.\n"
        return blob
    else:
        blob = "No search query is needed for a response"
    return blob

async def generate_response(instructions, search, history):
    search_results = search if search is not None else "Search feature is disabled"
    messages = [
            {"role": "system", "content": instructions},
            *history,
            {"role": "system", "content": search_results},
        ]
    response = await openai_client.chat.completions.create(
        model=config['GPT_MODEL'],
        messages=messages
    )
    message = response.choices[0].message.content
    return message

async def generate_grok_response(prompt):
    messages = [
            {"role": "user", "content": prompt},
        ]
    response = await openai_client.chat.completions.create(
        model=config['GPT_MODEL'],
        messages=messages
    )
    message = response.choices[0].message.content
    return message

async def poly_image_gen(prompt):
    response = await openai_client.images.generate(
        model="grok-imagine-image",
        prompt=prompt,
        n=1,
        response_format="b64_json",
    )
    image_data = base64.b64decode(response.data[0].url)
    return io.BytesIO(image_data)

async def generate_image_prodia(prompt, model, sampler, seed, neg):
    print("\033[1;32m(xAI) Creating image for :\033[0m", prompt)
    start_time = time.time()

    full_prompt = prompt
    if neg:
        full_prompt = f"{prompt}. Avoid: {neg}"

    response = await openai_client.images.generate(
        model="grok-imagine-image",
        prompt=full_prompt,
        n=1,
        response_format="b64_json",
    )
    image_data = base64.b64decode(response.data[0].url)
    img_file_obj = io.BytesIO(image_data)
    duration = time.time() - start_time
    print(f"\033[1;34m(xAI) Finished image creation\n\033[0mPrompt: {prompt} in {duration:.2f} seconds.")
    return img_file_obj
